steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update server
  entrypoint: '/bin/sh'
  args: 
  - '-c'
  - |
    set -x &&
    gcloud compute ssh --zone "us-west1-b" "lytro" --command="./pull.sh"